### ISSUE TITLE
SteamItem Type

### ISSUE THREAD

**Issue by Morb0** [timvandam/steam-inventory-iterator#1]
`SteamItem` type is not exported as type, it would be nice to have typing for items.

**Comment by Morb0** [comment]
And by declaring `Description` interface twice, you expanding first interface.

**Comment by timvandam** [comment]
> And by declaring `Description` interface twice, you expanding first interface.

Ah I didn't catch that. Thanks

**Comment by timvandam** [comment]
> `SteamItem` type is not exported as type, it would be nice to have typing for items.

I'm not sure how types work with dependencies. Does simply adding `export` work?

**Comment by Morb0** [comment]
> > `SteamItem` type is not exported as type, it would be nice to have typing for items.
> 
> I'm not sure how types work with dependencies. Does simply adding `export` work?

Maybe it will help you: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
I think need to set `types` path in package.json

**Comment by timvandam** [comment]
Yep, already did that in 1.0.1. Turns out types.d.ts isn't used when building

**Comment by Morb0** [comment]
And one more thing, item description have `fraudwarnings` field in some cases.
I think is info about trade ban after trade.

**Comment by timvandam** [comment]
Works now in 1.0.3
