### ISSUE TITLE
Inventory private Error

### ISSUE THREAD

**Issue by Morb0** [timvandam/steam-inventory-iterator#2]
Steam send 401 status code when user inventory is private.
What about add a specific error for that?

**Comment by timvandam** [comment]
Sure, sounds good. I’ll also think of a nice way to stop iterating when the inventory is private

**Comment by timvandam** [comment]
I suppose making every 4xx http code stop the iteration would work

**Comment by Morb0** [comment]
I'm sorry, I was wrong, I just double-checked it and Steam throws 403 (Forbidden) and `null` in the body. Based on this, the privacy error can be determined using these parameters and not completely capture the entire 4xx.

**Comment by timvandam** [comment]
https://github.com/timvandam/steam-inventory-iterator/tree/f4993ea78cbfe58970da764a17c59ff4654911a0

How's this?

**Comment by Morb0** [comment]
Everything look is fine, only the idea of automatically calling the `sleep` is not very good for me, it stops the thread and not allow to handle the error differently.

**Comment by timvandam** [comment]
It doesn’t stop the thread. You can change the timeout duration in RateLimitError

**Comment by timvandam** [comment]
You can set the timeout to 0 and handle it however you want

**Comment by timvandam** [comment]
Do you think removing that line entirely is better?

**Comment by Morb0** [comment]
> You can set the timeout to 0 and handle it however you want

Yes, you can really do it, then I think you just can write about that behavior in readme.

**Comment by timvandam** [comment]
Sure, will do
